server:
  port: 443
  address: 0.0.0.0

lavalink:
  server:
    password: "LAVA"
    playerUpdateInterval: 6
    koe:
      useEpoll: true
      highPacketPriority: true
      bufferDurationMs: 400
      byteBufAllocator: "default"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    lavaplayer:
      nonAllocating: true
      frameBufferDuration: 5000
      youtubePlaylistLoadLimit: 26
      gc-warnings: false
      youtubeSearchEnabled: true
      soundcloudSearchEnabled: true
      #ratelimit:
        #ipBlocks: ["1.0.0.0/8", "..."]
        #excludedIps: ["...", "..."]
        #strategy: "LoadBalance"
        #searchTriggersFail: true 
        #retryLimit: 0

metrics:
  prometheus:
    enabled: true
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    path: ./logs/
  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30

  level:
    root: INFO
    lavalink: INFO
